version: '2'

services:
  # gitlab:
  #     image: 'gitlab/gitlab-ce'
  #     restart: unless-stopped
  #     hostname: '192.168.3.59'
  #     environment:
  #       TZ: 'Beijing'
  #       GITLAB_OMNIBUS_CONFIG: |
  #         external_url 'http://192.168.3.59'
  #         gitlab_rails['time_zone'] = 'Beijing'
  #     ports:
  #       - '80:80'
  #       - '443:443'
  #       - '2222:22'
  drone-server:
    image: drone/drone:0.8
    ports:
      # - 8001:80
      # - 3001:443
      - 8001:8000
      - 9000:9000
    volumes:
      - /Users/donson/Documents/WorkSpace/share:/var/lib/drone/
    restart: always
    environment:
      - DRONE_HOST=http://192.168.3.59:8001
      - DRONE_OPEN=true
      - DRONE_GITLAB=true
      - DRONE_GITLAB_CLIENT=c649d320aad1248483ede118260dcebacb042eaa27b9c6c8e7efffa7d833b23f
      - DRONE_GITLAB_SECRET=78d82ae4c578e18bba50e101cb3fdefcf134428cbeced4549eb3cd93d5ca23ab
      - DRONE_GITLAB_URL=http://192.168.3.59:80
      - DRONE_SECRET=11111111
      - DRONE_GITLAB_GIT_USERNAME=root
      - DRONE_GITLAB_GIT_PASSWORD=11111111
      - DRONE_GITLAB_SKIP_VERIFY=true

  drone-agent:
    image: drone/agent:0.8

    restart: always
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_SERVER=drone-server:9000
      - DRONE_SECRET=11111111
