version: '2'
services:
    gitlab:
      image: 'gitlab/gitlab-ce'
      restart: unless-stopped
      hostname: '192.168.3.59'
      environment:
        TZ: 'Beijing'
        GITLAB_OMNIBUS_CONFIG: |
          external_url 'http://192.168.3.59'
          gitlab_rails['time_zone'] = 'Beijing'
          # 需要配置到 gitlab.rb 中的配置可以在这里配置，每个配置一行，注意缩进。
          # 比如下面的电子邮件的配置：
          # gitlab_rails['smtp_enable'] = true
          # gitlab_rails['smtp_address'] = "smtp.exmail.qq.com"
          # gitlab_rails['smtp_port'] = 465
          # gitlab_rails['smtp_user_name'] = "xxxx@xx.com"
          # gitlab_rails['smtp_password'] = "password"
          # gitlab_rails['smtp_authentication'] = "login"
          # gitlab_rails['smtp_enable_starttls_auto'] = true
          # gitlab_rails['smtp_tls'] = true
          # gitlab_rails['gitlab_email_from'] = 'xxxx@xxx.com'
      ports:
        - '80:80'
        - '443:443'
        - '2222:22'
      # volumes:
      #   - /var/lib/drone:/var/lib/drone/
