# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

platform :ios, "8.0"
inhibit_all_warnings!

target 'base-oc-framework' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for base-oc-framework
   pod 'AFNetworking', '~> 3.1.0’
   pod 'MBProgressHUD', '~> 0.9.1'
   pod 'Masonry', '~> 0.6.3'
   pod 'SDWebImage', '~> 3.7.3'
   pod 'ReactiveCocoa','~> 2.5'
   pod 'SDCycleScrollView','~> 1.65'
   pod 'IQKeyboardManager','~>4.0.7’
   pod 'MJExtension','~>3.0.13'
   pod 'TZImagePickerController'
   pod 'MJRefresh'
end
